version: "3.7"

services:
  db:
    image: mongo
    container_name: StarWars-mongo-container
    restart: always
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:21017

  db-ui:
    image: mongo-express
    container_name: StarWars-Mongo-Express-container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    links:
      - db
    depends_on:
      - db
  #sheet-crud:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #    target: builder
  #  security_opt:
  #    - apparmor:unconfined
  #  cap_add:
  #    - SYS_PTRACE
  #  ports:
  #    - "3000:3000" # application port
  #  command: [./app]
  #  restart: always
