version: "3.7"

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:21017
    volumes:
      - ./mongo-volume:/data/db

  db-ui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    links:
      - db
    depends_on:
      - db

  sheet-crud:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: ["./app"]
    restart: always
    links:
      - db
    depends_on:
      - db
    environment:
      DB_URI: mongodb://db:27017
